package com.vishwasena.urlshortener.repository;

import com.vishwasena.urlshortener.AbstractPostgresIntegrationTest;
import com.vishwasena.urlshortener.entity.ClickEvent;
import com.vishwasena.urlshortener.entity.ShortUrl;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.TestPropertySource;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@TestPropertySource(properties = "spring.flyway.enabled=true")
@Transactional
class ShortUrlRepositoryPostgresIntegrationTest extends AbstractPostgresIntegrationTest {

    @Autowired
    private ShortUrlRepository shortUrlRepository;

    @Autowired
    private ClickEventRepository clickEventRepository;

    @Test
    void testPostgresUniqueConstraintOnShortCode() {
        ShortUrl url1 = new ShortUrl("pgtest123", "https://example.com", "ACTIVE");
        shortUrlRepository.save(url1);

        ShortUrl url2 = new ShortUrl("pgtest123", "https://different.com", "ACTIVE");
        assertThrows(Exception.class, () -> {
            shortUrlRepository.saveAndFlush(url2);
        });
    }

    @Test
    void testPostgresBigSerialIdGeneration() {
        ShortUrl shortUrl = new ShortUrl("pgserial1", "https://example.com", "ACTIVE");
        ShortUrl saved = shortUrlRepository.save(shortUrl);

        assertNotNull(saved.getId());
        assertTrue(saved.getId() > 0, "ID should be generated by BIGSERIAL");
    }

    @Test
    void testPostgresTimestampWithTimeZone() {
        ShortUrl shortUrl = new ShortUrl("pgtz1", "https://example.com", "ACTIVE");
        shortUrl.setExpiresAt(OffsetDateTime.now().plusDays(1));
        ShortUrl saved = shortUrlRepository.save(shortUrl);

        Optional<ShortUrl> found = shortUrlRepository.findByShortCode("pgtz1");
        assertTrue(found.isPresent());
        assertNotNull(found.get().getExpiresAt());
        assertNotNull(found.get().getCreatedAt());
        assertNotNull(found.get().getUpdatedAt());
    }

    @Test
    void testPostgresCascadeDeleteClickEvents() {
        ShortUrl shortUrl = new ShortUrl("pgcascade1", "https://example.com", "ACTIVE");
        ShortUrl saved = shortUrlRepository.save(shortUrl);

        // Create multiple click events
        clickEventRepository.save(new ClickEvent(saved, "hash1", "Mozilla", null));
        clickEventRepository.save(new ClickEvent(saved, "hash2", "Chrome", null));

        long clickCount = clickEventRepository.countByShortUrlId(saved.getId());
        assertEquals(2, clickCount, "Should have 2 click events");

        // Delete short URL and verify CASCADE DELETE
        shortUrlRepository.deleteById(saved.getId());

        long remainingClicks = clickEventRepository.countByShortUrlId(saved.getId());
        assertEquals(0, remainingClicks, "Click events should be deleted via CASCADE");
    }

    @Test
    void testPostgresAnalyticsIndexPerformance() {
        ShortUrl shortUrl = new ShortUrl("pganalytics1", "https://example.com", "ACTIVE");
        ShortUrl saved = shortUrlRepository.save(shortUrl);

        // Record clicks with different IP hashes
        for (int i = 1; i <= 10; i++) {
            clickEventRepository.save(new ClickEvent(saved, "hash" + i, "Browser" + i, null));
        }

        // Query unique visitors (index on short_url_id should optimize this)
        long uniqueVisitors = clickEventRepository.countUniqueVisitors(saved.getId());
        assertEquals(10, uniqueVisitors, "Should count all unique IP hashes");
    }

    @Test
    void testPostgresClickEventOrder() {
        ShortUrl shortUrl = new ShortUrl("pgorder1", "https://example.com", "ACTIVE");
        ShortUrl saved = shortUrlRepository.save(shortUrl);

        OffsetDateTime t1 = OffsetDateTime.now();
        ClickEvent click1 = new ClickEvent(saved, "hash1", "Browser1", null);
        clickEventRepository.save(click1);

        OffsetDateTime t2 = OffsetDateTime.now().plusSeconds(1);
        ClickEvent click2 = new ClickEvent(saved, "hash2", "Browser2", null);
        clickEventRepository.save(click2);

        // Last clicked should be click2 (more recent)
        Optional<ClickEvent> lastClick = clickEventRepository.findFirstByShortUrlIdOrderByClickedAtDesc(saved.getId());
        assertTrue(lastClick.isPresent());
        assertEquals("hash2", lastClick.get().getIpHash());
    }
}
